name: gtk_window
description: A package that add some missing gtk4 windowing features to flutter.
homepage: https://lasheen.dev
repository: https://github.com/YoussefLasheen/gtk_window
version: 0.0.1

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  handy_window: ^0.1.9
  window_manager: ^0.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0